version: '3.0'

expectations:
  population_size: 10000

actions:

  
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2021-10-01 to 2021-10-08 by week" --output-dir=output
    outputs:
      highly_sensitive:
        cohort: output/input_*.csv


  # generate_study_population_practice_count:
  #   run: cohortextractor:latest generate_cohort --study-definition study_definition_practice_count --index-date-range "2021-06-01 to 2021-12-01 by month" --output-dir=output
  #   outputs:
  #     highly_sensitive:
  #       cohort: output/input_practice_count_*.csv

  generate_measures:
      run: cohortextractor:latest generate_measures --study-definition study_definition --output-dir=output
      needs: [generate_study_population]
      outputs:
        moderately_sensitive:
          measure_csv_1: output/measure_*_rate.csv
          measure_csv_2: output/measure_*_rate_by_region.csv
          measure_csv_3: output/measure_*_rate_by_comparator.csv
          measure_csv_4: output/measure_*_rate_by_value.csv
          # note the weekly files are not stored, only the compiled file
  
  calculate_rates:
      run: python:latest python analysis/rate_calculations.py
      needs: [generate_measures]
      outputs:
        moderately_sensitive:
          tables: output/comparator_rates_per_test.csv

  
  # create_notebook:
  #   run: python:latest python analysis/create_notebook.py
  #   outputs:
  #     moderately_sensitive:
  #       notebook: analysis/SRO_Notebook.ipynb

  # generate_notebook:
  #   run: jupyter:latest jupyter nbconvert /workspace/analysis/SRO_Notebook.ipynb --execute --to html --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400 --no-input
  #   needs: [create_notebook, calculate_rates, generate_study_population_practice_count]
  #   outputs:
  #     moderately_sensitive:
  #       notebook: output/SRO_Notebook.html

  # run_tests:
  #   run: python:latest python -m pytest --junit-xml=output/pytest.xml --verbose
  #   outputs:
  #     moderately_sensitive:
  #       log: output/pytest.xml
